apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksTask
  region: ap-south-1

nodeGroups:
- name: ng1
  desiredCapacity: 1
  instanceType: t2.micro
  ssh:
    publicKeyName: eks_key

- name: ng2
  desiredCapacity: 1
  instanceType: t2.micro
  ssh:
    publicKeyName: eks_key

#for using spot instances and on demand instances
- name: ngmixed
  minSize: 2
  maxSize: 5
  instancesDistribution:
    maxPrice: 0.015
    instanceTypes: ["t3.small" , "t3.medium"]
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 65
    spotInstancePools: 2
  ssh:
    publicKeyName: eks_key